// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tencent.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tencent.utils.CosHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class DownloadFileFromCOS extends CustomJavaAction<IMendixObject>
{
	/** @deprecated use TencentConnection.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __TencentConnection;
	private final tencent.proxies.ConnectionMaster TencentConnection;
	private final java.lang.String CosKey;
	/** @deprecated use FileDoc.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __FileDoc;
	private final tencent.proxies.FileDoc FileDoc;

	public DownloadFileFromCOS(
		IContext context,
		IMendixObject _tencentConnection,
		java.lang.String _cosKey,
		IMendixObject _fileDoc
	)
	{
		super(context);
		this.__TencentConnection = _tencentConnection;
		this.TencentConnection = _tencentConnection == null ? null : tencent.proxies.ConnectionMaster.initialize(getContext(), _tencentConnection);
		this.CosKey = _cosKey;
		this.__FileDoc = _fileDoc;
		this.FileDoc = _fileDoc == null ? null : tencent.proxies.FileDoc.initialize(getContext(), _fileDoc);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode LOG = Core.getLogger("TencentCOS.Download");
		if (FileDoc == null) {
            throw new IllegalArgumentException("fileDoc is null");
        }
		try {
            String rs = CosHelper.downloadToFileDocument(
                getContext(),
                FileDoc.getMendixObject(),
                TencentConnection.getsecretId(), TencentConnection.getsecretKey(), TencentConnection.getregionName(), TencentConnection.getbucketName(), CosKey
            );
            LOG.info("Download result: " + rs);

            // ตั้งชื่อไฟล์ให้ User เห็นถูกต้อง (CosHelper ก็เซ็ตให้แล้ว แต่เผื่ออยาก override เพิ่ม)
            String name = CosHelper.extractFileName(CosKey);
            FileDoc.setName(name);
            FileDoc.commit(getContext());

            return FileDoc.getMendixObject();
        } catch (Exception e) {
            LOG.error("Download failed for key=" + CosKey + " : " + e.getMessage(), e);
            throw e;
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DownloadFileFromCOS";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
