// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tencent.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class TestConnection extends CustomJavaAction<java.lang.Boolean>
{
	/** @deprecated use Parameter.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Parameter;
	private final tencent.proxies.ConnectionMaster Parameter;

	public TestConnection(
		IContext context,
		IMendixObject _parameter
	)
	{
		super(context);
		this.__Parameter = _parameter;
		this.Parameter = _parameter == null ? null : tencent.proxies.ConnectionMaster.initialize(getContext(), _parameter);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		String bucketName 	= this.Parameter.getbucketName();
		String regionName 	= this.Parameter.getregionName();
		String secretId 	= this.Parameter.getsecretId();
		String secretKey 	= this.Parameter.getsecretKey();
		
		return tencent.utils.CosHelper.testConnection(secretId, secretKey, regionName, bucketName);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TestConnection";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
