// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tencent.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tencent.utils.CosHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class UploadFileToCOS extends CustomJavaAction<java.lang.String>
{
	/** @deprecated use tencentConnection.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __tencentConnection;
	private final tencent.proxies.ConnectionMaster tencentConnection;
	/** @deprecated use fileDoc.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __fileDoc;
	private final tencent.proxies.FileDoc fileDoc;
	private final java.lang.String cosKey;

	public UploadFileToCOS(
		IContext context,
		IMendixObject _tencentConnection,
		IMendixObject _fileDoc,
		java.lang.String _cosKey
	)
	{
		super(context);
		this.__tencentConnection = _tencentConnection;
		this.tencentConnection = _tencentConnection == null ? null : tencent.proxies.ConnectionMaster.initialize(getContext(), _tencentConnection);
		this.__fileDoc = _fileDoc;
		this.fileDoc = _fileDoc == null ? null : tencent.proxies.FileDoc.initialize(getContext(), _fileDoc);
		this.cosKey = _cosKey;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode LOG = Core.getLogger("TencentCOS.Upload");

        if (fileDoc == null) throw new IllegalArgumentException("fileDoc is null");
        if (tencentConnection == null) throw new IllegalArgumentException("tencentConnection is null");
        if (cosKey == null || cosKey.isEmpty()) throw new IllegalArgumentException("cosKey is empty");

        // ชื่อไฟล์ที่จะโชว์บน Mendix (ใช้ชื่อเดิมของ FileDocument)
        String fileName = fileDoc.getName();
        if (fileName == null || fileName.isEmpty()) {
            // กรณีไม่มีชื่อ ให้ตัดจาก cosKey
            fileName = CosHelper.extractFileName(cosKey);
            fileDoc.setName(fileName);
            fileDoc.commit(getContext());
        }

        String result = CosHelper.uploadFileDocument(
                getContext(),
                fileDoc.getMendixObject(),
                tencentConnection.getsecretId(),
                tencentConnection.getsecretKey(),
                tencentConnection.getregionName(),
                tencentConnection.getbucketName(),
                cosKey
        );

        LOG.info("Upload result: " + result + " (cosKey=" + cosKey + ", fileName=" + fileName + ")");
        return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "UploadFileToCOS";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
