// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tencent.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.qcloud.cos.COSClient;
import com.qcloud.cos.model.COSObjectSummary;
import com.qcloud.cos.model.ListObjectsRequest;
import com.qcloud.cos.model.ObjectListing;
import tencent.utils.CosHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ViewFileList extends CustomJavaAction<java.util.List<IMendixObject>>
{
	/** @deprecated use Parameter.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Parameter;
	private final tencent.proxies.ConnectionMaster Parameter;
	private final java.lang.String Preflix;

	public ViewFileList(
		IContext context,
		IMendixObject _parameter,
		java.lang.String _preflix
	)
	{
		super(context);
		this.__Parameter = _parameter;
		this.Parameter = _parameter == null ? null : tencent.proxies.ConnectionMaster.initialize(getContext(), _parameter);
		this.Preflix = _preflix;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode LOG = Core.getLogger("TencentCOS.ViewFileList");
		List<IMendixObject> result = new ArrayList<>();

		COSClient cosClient = CosHelper.createClient(Parameter.getsecretId(), Parameter.getsecretKey(), Parameter.getregionName());

		try {
			ListObjectsRequest req = new ListObjectsRequest();
			req.setBucketName(Parameter.getbucketName());
			if (Preflix != null && !Preflix.isEmpty()) {
				String p = Preflix.endsWith("/") ? Preflix : Preflix + "/";
				req.setPrefix(p);
			}
			req.setDelimiter("/");
			req.setMaxKeys(1000);

			ObjectListing ol = cosClient.listObjects(req);

			while (true) {
				for (COSObjectSummary s : ol.getObjectSummaries()) {
					IMendixObject o = Core.instantiate(getContext(), "Tencent.TencentViewFile");
					o.setValue(getContext(), "Key",  s.getKey());
					o.setValue(getContext(), "Size", s.getSize());
					o.setValue(getContext(), "IsFolder", false);
					result.add(o);
				}

				for (String p : ol.getCommonPrefixes()) {
					IMendixObject o = Core.instantiate(getContext(), "Tencent.TencentViewFile");
					o.setValue(getContext(), "Key",  p);
					o.setValue(getContext(), "Size", 0L);
					o.setValue(getContext(), "IsFolder", true);
					result.add(o);
				}

				if (!ol.isTruncated()) break;
				ol = cosClient.listNextBatchOfObjects(ol);
			}

			LOG.info(String.format("✅ Listed %d entries (bucket=%s, prefix=%s)", result.size(), Parameter.getbucketName(), Preflix));

		} catch (Exception e) {
			LOG.error("❌ Failed to list objects: " + e.getMessage(), e);
		} finally {
			cosClient.shutdown();
		}

		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ViewFileList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
